POST http://127.0.0.1:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Cleitin na Hornet de Juju",
    "birthDate": "1997-04-29",
    "email": "cleitin@gmail.com",
    "password": "123456789",
    "gender": "Male"
}
###

POST http://127.0.0.1:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "cleitin@gmail.com",
    "password": "123456789"
}
###

GET http://127.0.0.1:3000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwODhjZDhiMC05ODNmLTQ3OGMtYmRmZi02NDE4MmExNDFmMTQiLCJzdWIiOiI4NDM2M2Q5OC03YzdkLTRkZWMtODJhNy1hZTdiOTgzNzA1N2YiLCJpYXQiOjE3MDI2OTEwNTEsImVtYWlsIjoiY2xlaXRpbkBnbWFpbC5jb20iLCJleHAiOjE3MDI2OTgyNTF9.rG_UIvG92BTT_LP1bRahTV791D14GTQwOHK61BuIIEk
###

GET http://127.0.0.1:3000/api/v1/users/875d867f-d966-4372-a30f-883c1f7ff7cd1 HTTP/1.1
###

POST http://127.0.0.1:3000/api/v1/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NGRiYmUzMS1hOTllLTQ1MTQtYThmYy0yMDkyZWUwOTA1NGEiLCJzdWIiOiI4NDM2M2Q5OC03YzdkLTRkZWMtODJhNy1hZTdiOTgzNzA1N2YiLCJpYXQiOjE3MDI2OTEzNDgsImVtYWlsIjoiY2xlaXRpbkBnbWFpbC5jb20iLCJleHAiOjE3MDI2OTg1NDh9.TtgxA9xEOzGvXKzkkoh3okR5xCw10XCXpBYcicOCPl4

{
    "images": ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAJCAYAAAAPU20uAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABZSURBVChTbY5bDoAwCARZ/j2c9z+LRZZ2K0YnmUBbHsVxjrAfhqOiX4B1+UCRbdSVSBsrLjwirEsYdPa6aago55RZMJPuawK4M/W87Iq9YnY9iv3JL1wHuwE8m0RIOtWIDQAAAA5lWElmTU0AKgAAAAgAAAAAAAAA0lOTAAAAAElFTkSuQmCC"],
    "title": "Postinho muito bacaninho sobre a corzinha azulinha",
    "content": "Lorem ipsum dolor sic aet"
}
###